### PR TITLE
Making a downgrade.bat

### PR DESCRIPTION
**Pull request by DennisLiu199**

### CODE REVIEW

**Comment by Cloud-121** [comment]
This is interesting ^^

**Comment by DylDevs** [comment]
Nobody would use this it's just more clutter in the folder

**Comment by DylDevs** [comment]
An option in app to do this would be nice though

**Comment by Cloud-121** [comment]
> Nobody would use this it's just more clutter in the folder

This is why I'm referencing in discord, would be interesting as a advanced option.

**Comment by DennisLiu199** [comment]
> An option in app to do this would be nice though

i think a perfect app don't need a downgrade option this just for beta testing only xdd

**Comment by DylDevs** [comment]
If it's for testing, it doesn't need to be pushed to the main repo.

**Comment by DylDevs** [comment]
But save this code because an option in the app to downgrade from a broken update would be good, but not directly as a batch file.

**Comment by DylDevs** [comment]
Gonna close due to inactivity, if you ever add something or implement it in the app, feel free to reopen this PR.

**Pull request closed without merging**
