### PR TITLE
change the window‘s width and height min

### PR DESCRIPTION
**Pull request by MRUIAW**
change the window width min from 960 to 0
change the window height min from 480 to 0

### CODE REVIEW

**Comment by MRUIAW** [comment]
WAIT

**Comment by MRUIAW** [comment]
ok done

**Comment by DylDevs** [comment]
?

**Comment by DylDevs** [comment]
Theres a minimum for a reason to make sure text is readable

**Comment by Tumppi066** [comment]
Have you tested that the UI is usable at this resolution. Last time the reason I set the minimums so high is that without them it was not possible to revert the width and height back.

ie. You set the width and height to 100x70, you can no longer go back to the settings to set it back.

**Comment by Tumppi066** [comment]
If the UI is usable then it's fine, but if it's not then we will keep the current values

**Comment by MRUIAW** [comment]
> Have you tested that the UI is usable at this resolution. Last time the reason I set the minimums so high is that without them it was not possible to revert the width and height back.您是否测试过 UI 在该分辨率下可用。上次我将最小值设置得这么高的原因是，如果没有它们，就不可能恢复宽度和高度。
> 
> ie. You set the width and height to 100x70, you can no longer go back to the settings to set it back.IE。您将宽度和高度设置为 100x70，您无法再返回设置来重新设置它。

tried it, but i guess the resolution and the scaling level in Windows settings will also affect that

**Comment by MRUIAW** [comment]
ummmmm.....

**Pull request closed without merging**
