### PR TITLE
Add Cruise Control Plugin.

### PR DESCRIPTION
**Pull request by MRUIAW**
Add Cruise Control Plugin
Add English translation for Cruise Control
Add Chinese (Simplified) translation for Cruise Control

### CODE REVIEW

**Review by DylDevs — CHANGES_REQUESTED** [review]
- You'll need to update the keys.json file with the new translation keys (along with comments.json if needed)
- Remove the cache folder

**Comment by MRUIAW** [comment]
oh i forgot that
sec

**Comment by MRUIAW** [comment]
done i think
already have those keys in the keys.json

**Comment by DylDevs** [comment]
Yep my bad I didnt realize that you just updated the keys

**Review by DylDevs — APPROVED** [review]

**Pull request merged**
